### ISSUE TITLE
Viewdata doesn't render properly

### ISSUE THREAD

**Issue by nelgin** [mkrueger/icy_tools#32]
Hi there,

I'm not sure if this is a limitation due to graphics or something, but the display isn't rendering properly.

https://ctrl.vi/i/70TJZC8yn

Also, _ should display as #.

**Comment by nelgin** [comment]
Should have said, this is at endofthelinebbs.com port 6502 which uses 7E1. I have similar issues with glasstty.com port 6502.

**Comment by mkrueger** [comment]
Doesn't seem you've enabled  the correct screen mode. You need to set it to "VIDEOTEX" - for technical reasons parser & screenmode are different things.  However in the UI I need to represent that differently because in fact for many legacy systems like C64/Atari/ViewData it's tightly connected. For some like DOS it's not.

![image](https://github.com/user-attachments/assets/19a176f2-b26b-42f9-9ad7-84f6c3626185)

**Comment by mkrueger** [comment]
![image](https://github.com/user-attachments/assets/09ffb91c-43a9-40a5-9cf3-5606aa20e551)
